CREATE OR REPLACE PROCEDURE REMOVER_INDEXES (TABLE_N IN VARCHAR2) IS
BEGIN
    FOR i IN (
        SELECT INDEX_NAME
        FROM DBA_IND_COLUMNS
        WHERE TABLE_NAME = TABLE_N
    ) LOOP
        IF CONCAT('PK_', TABLE_N) <> i.INDEX_NAME THEN
            EXECUTE IMMEDIATE 'DROP INDEX ' || i.INDEX_NAME;
        END IF;
    END LOOP;
END REMOVER_INDEXES;

/*
 CRIA UM INDICE NA TABELA ALBUM PARA PODER REMOVE-LO, JÁ
 QUE O ORACLE XE NÃO PERMITE A REMOÇÃO DE PRIMARY KEYS.
*/

CREATE INDEX INDEX_TESTE ON ALBUM(TITLE);
SELECT INDEX_NAME FROM DBA_IND_COLUMNS WHERE TABLE_NAME = 'ALBUM';

CALL REMOVER_INDEXES('ALBUM');
SELECT INDEX_NAME FROM DBA_IND_COLUMNS WHERE TABLE_NAME = 'ALBUM';
