SELECT DC.CONSTRAINT_NAME,
       DC.TABLE_NAME,
       DCC.COLUMN_NAME
FROM DBA_CONSTRAINTS DC
    JOIN DBA_CONS_COLUMNS DCC
    ON DC.CONSTRAINT_NAME = DCC.CONSTRAINT_NAME
WHERE DC.OWNER = 'CHINOOK' AND DC.CONSTRAINT_TYPE = 'R';


SELECT * FROM DBA_CONSTRAINTS WHERE OWNER = 'CHINOOK' AND CONSTRAINT_TYPE = 'P';


SELECT DC.CONSTRAINT_NAME,
       DC.TABLE_NAME,
       DCC.COLUMN_NAME
FROM DBA_CONSTRAINTS DC
    JOIN DBA_CONS_COLUMNS DCC
    ON DC.CONSTRAINT_NAME = DCC.CONSTRAINT_NAME
WHERE DC.OWNER = 'CHINOOK' AND DC.CONSTRAINT_TYPE = 'P';
