DROP TRIGGER EMPLOYEE_INSERT;
CREATE OR REPLACE TRIGGER EMPLOYEE_INSERT BEFORE INSERT ON EMPLOYEE
    FOR EACH ROW
    BEGIN
        IF (SELECT BIRTHDATE FROM EMPLOYEE  WHERE TIMESTAMPDIFF(YEAR, :NEW.BIRTHDATE, CURRENT_DATE()) < 18)
            THEN
            RAISE_APPLICATION_ERROR (-20202, 'Employee must have 18 years old or more');
        END IF;
    END;

INSERT INTO EMPLOYEE (EMPLOYEEID, LASTNAME, FIRSTNAME, TITLE, REPORTSTO, BIRTHDATE, HIREDATE, ADDRESS, CITY, STATE, COUNTRY, POSTALCODE, PHONE, FAX, EMAIL)
VALUES (2221, N'Moreira', N'Carlos', 'Estagiário', NULL ,TO_DATE('2010-11-6 00:00:00','yyyy-mm-dd hh24:mi:ss'),TO_DATE('2020-8-14 00:00:00','yyyy-mm-dd hh24:mi:ss'), '123 Amaral Peixoto', 'Niterói', 'Rio de Janeiro', 'Brasil', '+55','+1 (21) 99232-3152','+1 (21) 24284-2841', 'carlosmoreira@gmail.com');
